### ISSUE TITLE
Creating the first release

### ISSUE THREAD

**Issue by JCWolf** [cpanato/mattermost-plugin-aws-SNS#1]
It is possible to have the first release for this plugin? My company requires it, unfortunately.

**Comment by cpanato** [comment]
@JCWolf doing that, sorry for the delay, just saw now

**Comment by JCWolf** [comment]
Thank you! 😃

**Comment by cpanato** [comment]
@JCWolf here: https://github.com/cpanato/mattermost-plugin-aws-SNS/releases/tag/v0.1.0
